# Generated by Django 2.1 on 2019-02-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_product_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='product_description',
        ),
    ]
